// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BooksindexController from "./booksindex_controller"
application.register("booksindex", BooksindexController)

import EditTagController from "./edit_tag_controller"
application.register("edit-tag", EditTagController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HighlightController from "./highlight_controller"
application.register("highlight", HighlightController)
